# -*- coding: utf-8 -*-
"""fiap-ia-2ano-fase1-cap1

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1tMGtZc76wADN1jPtn71qdaCGm08d7YDA

# script Python para converter MIT-BIH em imagem e csv

4️⃣ Faça upload do arquivo:
"""

from google.colab import files
uploaded = files.upload()

"""✔ Depois extraia o projeto"""

import zipfile

with zipfile.ZipFile('cardioia_fase1_profissional.zip', 'r') as zip_ref:
    zip_ref.extractall('/content')

"""✔ Verifique se carregou"""

!ls /content/cardioia_fase1_profissional

"""✔ Instalar dependências"""

!pip install wfdb matplotlib pandas numpy openpyxl

"""Gerar o dataset cardiológico (300 linhas)"""

!python /content/cardioia_fase1_profissional/scripts/generate_cardiology_dataset.py --rows 300 --output_dir /content/cardioia_fase1_profissional/datasets

"""Converter MIT-BIH em 100 imagens

Primeiro faça upload do dataset MIT-BIH.
"""

from google.colab import files
files.upload()

"""✔ Passo 1 — Verificar o que foi enviado"""

!ls /content

"""✔ Passo 2 — Descompactar o dataset"""

!unzip mit-bih-arrhythmia-database-1.0.0.zip -d /content/

!ls /content

!python /content/cardioia_fase1_profissional/scripts/convert_mitbih_to_images.py \
--input_dir "/content/mit-bih-arrhythmia-database-1.0.0" \
--output_dir "/content/cardioia_fase1_profissional/assets/ecg_images" \
--limit 100

!ls /content/cardioia_fase1_profissional/assets/ecg_images

"""Baixe as imagens geradas"""

!zip -r ecg_images.zip /content/cardioia_fase1_profissional/assets/ecg_images

"""Copacte e baixe os arquivos"""

from google.colab import files
files.download("ecg_images.zip")

"""PASSO 2 - GERAR DATASET NUMÉRICO"""

!python /content/cardioia_fase1_profissional/scripts/generate_cardiology_dataset.py \
--rows 300 \
--output_dir /content/cardioia_fase1_profissional/datasets

"""Baixar o arquivo csv"""

from google.colab import files

files.download('/content/cardioia_fase1_profissional/datasets/pacientes_cardiacos_300.csv')

"""Baixar o arquivo xlsx"""

from google.colab import files

files.download('/content/cardioia_fase1_profissional/datasets/pacientes_cardiacos_300.xlsx')

"""Se preferir pode compactar e baixar o csv e xlsx juntos"""

!zip -r cardioia_resultado.zip /content/cardioia_fase1_profissional

from google.colab import files
files.download("cardioia_resultado.zip")